name: Deploy on PythonAnywhere

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to PythonAnywhere via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ssh.pythonanywhere.com
          username: gmartinezjr
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/gmartinezjr/mysite/web
            git pull origin main
            pip3 install -r requirements.txt
            touch /var/www/www.coderscomerciales_com_wsgi.py
